### ISSUE TITLE
Implement select game section

### ISSUE THREAD

**Issue by apsdehal** [yoav-zibin/NewGamePortal#3]
For new game portal, implement section that will be used to select a game to play. Should:

- Display all of the game spec names
- Should be selectable
- Should be searchable.

Start from static approach by hardcoding spec names, then when done, add bindings to firebase.

**Comment by apsdehal** [comment]
@xiaozdezhu Your issue.

**Comment by xiaozdezhu** [comment]
I read a lot of materials about redux, but I am still confused about how to use it.
Therefore I just write something according to my understanding so far.

**Comment by yoav-zibin** [comment]
You can watch these great videos:
*this great video playlist
<http://www.youtube.com/playlist?list=PL6gx4Cwl9DGBbSLZjvleMwldX8jGgXV6a>*
https://www.youtube.com/playlist?list=PL6gx4Cwl9DGBbSLZjvleMwldX8jGgXV6a
